rec {
  hostName = "drhorrible";
  device = "801cc75b-726d-b24a-b46b-7015fb5bf9cd";

  roles = [ "forge" ];

  apps = [
    "fort-tokens"
    "homepage"
    "overlay-registry"
    "pocket-id"
    "provisioner"
  ];

  overlays = {
    # Coffer secrets broker (server role: coffer-server + coffer-web).
    # CI registers the overlay on push to main once go.mod exists.
    coffer = {
      package = "infra/coffer";
      config = {
        role = "server";
        port = "7787";
        webPort = "7788";
      };
      # coffer-web at https://coffer.<domain>, VPN-only (default visibility).
      # identity mode has nginx auth_request inject X-Forwarded-User — exactly
      # the header coffer-web trusts (auth_header default). coffer-web itself
      # refuses requests without it, so nothing reaches the core unauthenticated
      # even if nginx is misconfigured. The mTLS machine API on :7787 is
      # untouched — this fronts only the human surface on :7788.
      expose = {
        subdomain = "coffer";
        port = 7788;
        sso = { mode = "identity"; groups = [ "admin" ]; };
      };
    };
  };
  aspects = [
    "mesh"
    "observable"
    "ldap"
    "backup-client"
    { name = "gitops"; manualDeploy = true; }
  ];

  module =
    { config, ... }:
    {
      config.fort.host = { inherit roles apps aspects; };

      # Coffer operator config (BRIEF-v0 §3/§8, amended by q-55748ea0). The
      # TOML is config, not Coffer state: paths under /var/lib/coffer are
      # operator-supplied material populated by the one-time ceremony
      # (OPERATIONS.md in the coffer repo): server.crt/server.key — the
      # server's own self-signed TLS pair, the only cert material needed.
      # There is NO CA and no client trust-anchor bundle: clients present
      # self-signed certs wrapping their existing host keys, and Coffer
      # pins the key (SPKI) via the approved-machines table.
      # recipient.key, master.key.wrapped, and grant.key are generated by
      # coffer-server on first boot; the recovery recipient below is the
      # offline holder's age PUBLIC key, consumed only when wrapping the
      # master key on first boot.
      config.users.users.coffer = {
        isSystemUser = true;
        group = "coffer";
        home = "/var/lib/coffer";
      };
      config.users.groups.coffer = { };
      config.environment.etc."coffer/server.toml".text = ''
        db_path = "/var/lib/coffer/coffer.db"
        tls_cert = "/var/lib/coffer/server.crt"
        tls_key = "/var/lib/coffer/server.key"
        listen = ":7787"
        recipient_key = "/var/lib/coffer/recipient.key"
        master_key_wrapped = "/var/lib/coffer/master.key.wrapped"
        recovery_recipient = "age17naqzhmwxza5mkzss0v2ytzwge209awezfrw6u6pvtug5t68zp7shgrvr8"
        grant_key = "/var/lib/coffer/grant.key"
      '';
      # coffer-web is a client of the audited core, onboarded like any
      # machine (OPERATIONS.md runbook): its own self-signed client cert
      # wrapping its own ed25519 key (web.crt/web.key, operator-minted),
      # trust_anchors pointing at the server's own cert, and a human-scoped
      # grant token (web.grant, minted via coffer-admin) — then one explicit
      # POST /v1/register + admin approval pins its key. The server URL dials
      # "drhorrible" (in the server cert's SAN set); 127.0.0.1 is not a SAN.
      config.environment.etc."coffer/web.toml".text = ''
        server = "https://drhorrible:7787"
        # Belt-and-suspenders for q-5cedc922: the overlay exec already passes
        # --listen 127.0.0.1:7788; pinning it here too keeps coffer-web off
        # the mesh even if the overlay flag is ever dropped. coffer-web trusts
        # X-Forwarded-User from the host-local identity proxy, so a mesh-
        # reachable bind would let any mesh process forge it.
        listen = "127.0.0.1:7788"
        tls_cert = "/var/lib/coffer/web.crt"
        tls_key = "/var/lib/coffer/web.key"
        trust_anchors = "/var/lib/coffer/server.crt"
        grant_file = "/var/lib/coffer/web.grant"
      '';
      config.systemd.tmpfiles.rules = [
        "d /var/lib/coffer 0750 coffer coffer -"
        # Operator-minted TLS material is created as root (the coffer user
        # does not exist until this generation activates); fix ownership so
        # coffer-server can read its key. z = adjust existing, no-op if absent.
        "z /var/lib/coffer/server.crt 0644 coffer coffer -"
        "z /var/lib/coffer/server.key 0600 coffer coffer -"
        "z /var/lib/coffer/web.crt 0644 coffer coffer -"
        "z /var/lib/coffer/web.key 0600 coffer coffer -"
        "z /var/lib/coffer/web.grant 0600 coffer coffer -"
        "L+ /var/lib/coffer/server.toml - - - - /etc/coffer/server.toml"
        "L+ /var/lib/coffer/web.toml - - - - /etc/coffer/web.toml"
      ];
    };
}
