rec {
  hostName = "drhorrible";
  device = "801cc75b-726d-b24a-b46b-7015fb5bf9cd";

  roles = [ "forge" ];

  apps = [
    "fort-tokens"
    "homepage"
    "overlay-registry"
    "pocket-id"
    "provisioner"
  ];

  overlays = {
    # Coffer secrets broker (server role: coffer-server + coffer-web).
    # CI registers the overlay on push to main once go.mod exists.
    coffer = {
      package = "infra/coffer";
      config = {
        role = "server";
        port = "7787";
        webPort = "7788";
      };
    };
  };
  aspects = [
    "mesh"
    "observable"
    "ldap"
    "backup-client"
    { name = "gitops"; manualDeploy = true; }
  ];

  module =
    { config, ... }:
    {
      config.fort.host = { inherit roles apps aspects; };

      # Coffer operator config (BRIEF-v0 §3/§8). The TOML is config, not
      # Coffer state: paths under /var/lib/coffer are operator-supplied
      # material populated by the one-time ceremony (OPERATIONS.md in the
      # coffer repo): trust-anchors.pem (client-cert CA bundle — NOTE: fort
      # has no machine-identity CA yet; creating one is part of the
      # ceremony), server.crt/server.key (externally issued TLS pair).
      # recipient.key, master.key.wrapped, and grant.key are generated by
      # coffer-server on first boot; the recovery recipient below is the
      # offline holder's age PUBLIC key, consumed only when wrapping the
      # master key on first boot.
      config.users.users.coffer = {
        isSystemUser = true;
        group = "coffer";
        home = "/var/lib/coffer";
      };
      config.users.groups.coffer = { };
      config.environment.etc."coffer/server.toml".text = ''
        db_path = "/var/lib/coffer/coffer.db"
        trust_anchors = "/var/lib/coffer/trust-anchors.pem"
        tls_cert = "/var/lib/coffer/server.crt"
        tls_key = "/var/lib/coffer/server.key"
        listen = ":7787"
        recipient_key = "/var/lib/coffer/recipient.key"
        master_key_wrapped = "/var/lib/coffer/master.key.wrapped"
        recovery_recipient = "age17naqzhmwxza5mkzss0v2ytzwge209awezfrw6u6pvtug5t68zp7shgrvr8"
        grant_key = "/var/lib/coffer/grant.key"
      '';
      config.systemd.tmpfiles.rules = [
        "d /var/lib/coffer 0750 coffer coffer -"
        "L+ /var/lib/coffer/server.toml - - - - /etc/coffer/server.toml"
      ];
    };
}
