[devices]

[devices.b7e58d48-241c-1a4a-8eea-dc90095d4ec7]
profile = "beelink"
system = "x86_64-linux"
pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEkox9tTdQLF+g11Pd+m0udiQW9Edfvz7sl0+L0RPgDK fort-device-b7e58d48-241c-1a4a-8eea-dc90095d4ec7"

[devices.8e9779b1-a912-744c-930a-08b4d2e87425]
profile = "beelink"
system = "x86_64-linux"
pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILXYyg91IkjZp9DnaHJHt9giTsmJXPw0YE8xIqtoMsco fort-device-8e9779b1-a912-744c-930a-08b4d2e87425"

[devices.17f17980-5d30-11f0-9a98-fe3a96b43f00]
profile = "evo-x2"
system = "x86_64-linux"
pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILSyr6yZ0QKeebgAg497+EO5f9VLcvBJbEHxaDzLzUxM fort-device-17f17980-5d30-11f0-9a98-fe3a96b43f00"

[settings]
pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC1fUAZLXWXgXfTKxejJHTT8rLpmDoTdJOxDV5m3lUHp fort"
registry_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM1afmFa8Ox6Rrij6RgZytyBugPY1Hrw/F8xgEVMVnHk fort-dns-registry"
domain = "gisi.network"

[hosts]

[hosts.lordhenry]
device = "17f17980-5d30-11f0-9a98-fe3a96b43f00"

[hosts.richardiii]
device = "b7e58d48-241c-1a4a-8eea-dc90095d4ec7"
roles = [ "fort-nameserver" ]

[hosts.ursula]
device = "8e9779b1-a912-744c-930a-08b4d2e87425"
drivers = [ "media-raid" ]
services = [ "jellyfin" ]
