# Mandatory control-plane capability handlers (q-1f08acd9)
#
# Shared by both platforms: every handler either works identically on NixOS
# and darwin or carries an explicit isDarwin branch (systemctl/journalctl vs
# launchctl/log-show). Imported by common/fort/control-plane.nix, which
# installs these under /etc/fort/handlers/ on both platforms.
#
# NOTE: sanitizeJournalOutput is shared by the Linux and darwin journal
# handlers — changing it changes every host's drv on both platforms.
{ pkgs, lib, config, isDarwin, hostName, fortProvider }:
let
  sanitizeJournalOutput = pkgs.writeText "sanitize-journal-output.py" ''
    import json
    import sys

    path, lines_requested, line_limit, max_chars, max_line_chars, line_limit_clamped, char_limit_clamped, max_line_chars_clamped = sys.argv[1:]
    lines_requested = int(lines_requested)
    line_limit = int(line_limit)
    max_chars = int(max_chars)
    max_line_chars = int(max_line_chars)
    line_limit_clamped = line_limit_clamped == "true"
    char_limit_clamped = char_limit_clamped == "true"
    max_line_chars_clamped = max_line_chars_clamped == "true"

    HEAD_CHARS = 300
    TAIL_CHARS = 200

    output_lines = []
    chars_returned = 0
    lines_seen = 0
    long_lines_truncated = 0
    total_budget_truncated = False

    def truncate_long_line(line, limit):
        if len(line) <= limit:
            return line, False
        omitted = len(line) - HEAD_CHARS - TAIL_CHARS
        if omitted > 0 and HEAD_CHARS + TAIL_CHARS < len(line):
            marker = f"...[omitted {omitted} chars]..."
            truncated = line[:HEAD_CHARS] + marker + line[-TAIL_CHARS:]
        else:
            truncated = line[:limit] + f"...[truncated: omitted {len(line) - limit} chars]"
        return truncated, True

    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for raw in f:
            lines_seen += 1
            line = raw[:-1] if raw.endswith("\n") else raw
            if len(line) > max_line_chars:
                line, was_truncated = truncate_long_line(line, max_line_chars)
                if was_truncated:
                    long_lines_truncated += 1

            separator_len = 1 if output_lines else 0
            remaining = max_chars - chars_returned - separator_len
            if remaining <= 0:
                total_budget_truncated = True
                break
            if len(line) > remaining:
                output_lines.append(line[:remaining] + f"...[char budget {max_chars} reached]")
                total_budget_truncated = True
                break

            output_lines.append(line)
            chars_returned += separator_len + len(line)

    output = "\n".join(output_lines)
    truncated = total_budget_truncated or long_lines_truncated > 0 or lines_seen > len(output_lines)
    response = {
        "output": output,
        "lines_requested": lines_requested,
        "line_limit": line_limit,
        "lines_returned": len(output_lines),
        "chars_returned": len(output),
        "char_limit": max_chars,
        "max_line_chars": max_line_chars,
        "truncated": truncated,
        "line_limit_clamped": line_limit_clamped,
        "char_limit_clamped": char_limit_clamped,
        "max_line_chars_clamped": max_line_chars_clamped,
        "long_lines_truncated": long_lines_truncated,
    }
    if truncated or line_limit_clamped or char_limit_clamped or max_line_chars_clamped:
        response["continuation"] = "Request fewer lines, narrower since/unit/identifier filters, add grep to filter, or pass larger max_chars/max_line_chars if you need omitted content."
    print(json.dumps(response))
  '';
in
{
    # Return host status (generated by host-status aspect timer)
    # Merges in provider state summary if present
    status = pkgs.writeShellScript "handler-status" (if isDarwin then ''
      # Get base status
      if [ -f /var/lib/fort/status/status.json ]; then
        base_status=$(${pkgs.coreutils}/bin/cat /var/lib/fort/status/status.json)
      else
        # Fallback: derive uptime from kern.boottime on macOS
        boot_epoch=$(/usr/sbin/sysctl -n kern.boottime | ${pkgs.gnused}/bin/sed 's/{ sec = \([0-9]*\).*/\1/')
        now_epoch=$(${pkgs.coreutils}/bin/date +%s)
        uptime_secs=$((now_epoch - boot_epoch))
        base_status=$(${pkgs.jq}/bin/jq -n \
          --arg hostname "${hostName}" \
          --argjson uptime "$uptime_secs" \
          --arg generated "$(${pkgs.coreutils}/bin/date -Iseconds)" \
          '{hostname: $hostname, status: "unknown", uptime_seconds: $uptime, generated_at: $generated}')
      fi

      # Add provider state summary if present
      if [ -f /var/lib/fort/provider-state.json ]; then
        provider_summary=$(${pkgs.jq}/bin/jq 'to_entries | map({key: .key, value: (.value | length)}) | from_entries' \
          /var/lib/fort/provider-state.json)
        base_status=$(echo "$base_status" | ${pkgs.jq}/bin/jq --argjson ps "$provider_summary" '. + {provider_state: $ps}')
      fi

      # Add consumer state (fulfillment) if present
      if [ -f /var/lib/fort/fulfillment-state.json ]; then
        consumer_summary=$(${pkgs.jq}/bin/jq 'to_entries | map({key: .key, value: .value.satisfied}) | from_entries' \
          /var/lib/fort/fulfillment-state.json)
        base_status=$(echo "$base_status" | ${pkgs.jq}/bin/jq --argjson cs "$consumer_summary" '. + {consumer_state: $cs}')
      fi

      echo "$base_status"
    '' else ''
      # Get base status
      if [ -f /var/lib/fort/status/status.json ]; then
        base_status=$(${pkgs.coreutils}/bin/cat /var/lib/fort/status/status.json)
      else
        # Fallback if status.json doesn't exist yet
        uptime_secs=$(${pkgs.coreutils}/bin/cut -d' ' -f1 /proc/uptime | ${pkgs.coreutils}/bin/cut -d. -f1)
        base_status=$(${pkgs.jq}/bin/jq -n \
          --arg hostname "${hostName}" \
          --argjson uptime "$uptime_secs" \
          --arg generated "$(${pkgs.coreutils}/bin/date -Iseconds)" \
          '{hostname: $hostname, status: "unknown", uptime_seconds: $uptime, generated_at: $generated}')
      fi

      # Add provider state summary if present
      if [ -f /var/lib/fort/provider-state.json ]; then
        provider_summary=$(${pkgs.jq}/bin/jq 'to_entries | map({key: .key, value: (.value | length)}) | from_entries' \
          /var/lib/fort/provider-state.json)
        base_status=$(echo "$base_status" | ${pkgs.jq}/bin/jq --argjson ps "$provider_summary" '. + {provider_state: $ps}')
      fi

      # Add consumer state (fulfillment) if present
      if [ -f /var/lib/fort/fulfillment-state.json ]; then
        consumer_summary=$(${pkgs.jq}/bin/jq 'to_entries | map({key: .key, value: .value.satisfied}) | from_entries' \
          /var/lib/fort/fulfillment-state.json)
        base_status=$(echo "$base_status" | ${pkgs.jq}/bin/jq --argjson cs "$consumer_summary" '. + {consumer_state: $cs}')
      fi

      echo "$base_status"
    '');

    # Return host manifest (apps, aspects, roles, exposedServices, capabilities)
    manifest = pkgs.writeShellScript "handler-manifest" ''
      ${pkgs.jq}/bin/jq -s '.[0] + {capabilities: .[1]}' \
        /var/lib/fort/host-manifest.json \
        /etc/fort/capabilities.json
    '';

    # Return list of declared needs (for GC enumeration)
    needs = let
      needsList = lib.concatLists (lib.mapAttrsToList (capability:
        lib.mapAttrsToList (name: _: "${capability}/${name}")
      ) config.fort.host.needs);
      needsListJson = builtins.toJSON needsList;
    in pkgs.writeShellScript "handler-needs" ''
      echo '{"needs":${needsListJson}}'
    '';

    # Fetch log output for a unit or syslog identifier (debug capability)
    journal = pkgs.writeShellScript "handler-journal" (if isDarwin then ''
      set -euo pipefail

      input=$(${pkgs.coreutils}/bin/cat)
      if ! echo "$input" | ${pkgs.jq}/bin/jq empty 2>/dev/null; then
        echo '{"error": "invalid request: expected JSON body, e.g. {\"unit\":\"nginx\",\"lines\":40}"}'
        exit 1
      fi
      unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')
      identifier=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.identifier // empty')
      lines_raw=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.lines // 40')
      max_chars_raw=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.max_chars // 8000')
      max_line_chars_raw=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.max_line_chars // 500')
      grep_pattern=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.grep // empty')
      since=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.since // empty')
      until=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.until // empty')

      if [ -z "$unit" ] && [ -z "$identifier" ]; then
        echo '{"error": "unit or identifier parameter required"}'
        exit 1
      fi
      if [ -n "$unit" ] && [ -n "$identifier" ]; then
        echo '{"error": "unit and identifier are mutually exclusive"}'
        exit 1
      fi
      for value_name in lines max_chars max_line_chars; do
        value_var="''${value_name}_raw"
        value="''${!value_var}"
        if ! [[ "$value" =~ ^[0-9]+$ ]] || [ "$value" -lt 1 ]; then
          ${pkgs.jq}/bin/jq -n --arg field "$value_name" --arg value "$value" '{"error": "invalid numeric parameter", "field": $field, "value": $value}'
          exit 1
        fi
      done

      lines_requested="$lines_raw"
      line_limit_clamped=false
      char_limit_clamped=false
      max_line_chars_clamped=false
      if [ "$lines_raw" -gt 100 ]; then
        lines=100
        line_limit_clamped=true
      else
        lines="$lines_raw"
      fi
      if [ "$max_chars_raw" -gt 100000 ]; then
        max_chars=100000
        char_limit_clamped=true
      else
        max_chars="$max_chars_raw"
      fi
      if [ "$max_line_chars_raw" -gt 10000 ]; then
        max_line_chars=10000
        max_line_chars_clamped=true
      else
        max_line_chars="$max_line_chars_raw"
      fi

      name="''${unit:-$identifier}"
      raw_file=$(${pkgs.coreutils}/bin/mktemp)
      trap 'rm -f "$raw_file"' EXIT

      # Launchd daemons in this cluster log via StandardOutPath to
      # /var/log/<name>.log — those messages never reach the unified log,
      # so prefer the log file when one exists (q-314c1d31). Try the name
      # as given, then with a network.gisi.* label mapped back to a file
      # name (network.gisi.fort.provider -> fort-provider).
      log_file=""
      for candidate in "/var/log/$name.log" "/var/log/$(echo "$name" | ${pkgs.gnused}/bin/sed 's/^network\.gisi\.//; s/\./-/g').log"; do
        if [ -f "$candidate" ]; then
          log_file="$candidate"
          break
        fi
      done

      if [ -n "$log_file" ]; then
        if [ -n "$grep_pattern" ]; then
          ${pkgs.gnugrep}/bin/grep -E -i -- "$grep_pattern" "$log_file" | ${pkgs.coreutils}/bin/tail -n "$lines" > "$raw_file" || true
        else
          ${pkgs.coreutils}/bin/tail -n "$lines" "$log_file" > "$raw_file" || true
        fi
      else
        # Fall back to the unified log. Include info/debug levels (log show
        # only emits default-level messages otherwise) and match on process
        # name, subsystem, or image path.
        predicate="process == \"$name\" OR subsystem == \"$name\" OR senderImagePath CONTAINS \"$name\" OR processImagePath CONTAINS \"$name\""

        args=("--predicate" "$predicate" "--style" "compact" "--info" "--debug" "--last" "1h")
        if [ -n "$since" ]; then
          args=("--predicate" "$predicate" "--style" "compact" "--info" "--debug" "--start" "$since")
        fi
        if [ -n "$until" ]; then
          args+=("--end" "$until")
        fi

        if [ -n "$grep_pattern" ]; then
          /usr/bin/log show "''${args[@]}" 2>&1 | ${pkgs.gnugrep}/bin/grep -E -i -- "$grep_pattern" | ${pkgs.coreutils}/bin/tail -n "$lines" > "$raw_file" || true
        else
          /usr/bin/log show "''${args[@]}" 2>&1 | ${pkgs.coreutils}/bin/tail -n "$lines" > "$raw_file" || true
        fi
      fi
      ${pkgs.python3}/bin/python3 ${sanitizeJournalOutput} "$raw_file" "$lines_requested" "$lines" "$max_chars" "$max_line_chars" "$line_limit_clamped" "$char_limit_clamped" "$max_line_chars_clamped"
    '' else ''
      set -euo pipefail

      input=$(${pkgs.coreutils}/bin/cat)
      if ! echo "$input" | ${pkgs.jq}/bin/jq empty 2>/dev/null; then
        echo '{"error": "invalid request: expected JSON body, e.g. {\"unit\":\"nginx\",\"lines\":40}"}'
        exit 1
      fi
      unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')
      identifier=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.identifier // empty')
      lines_raw=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.lines // 40')
      max_chars_raw=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.max_chars // 8000')
      max_line_chars_raw=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.max_line_chars // 500')
      grep_pattern=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.grep // empty')
      since=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.since // empty')
      until=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.until // empty')

      if [ -z "$unit" ] && [ -z "$identifier" ]; then
        echo '{"error": "unit or identifier parameter required"}'
        exit 1
      fi
      if [ -n "$unit" ] && [ -n "$identifier" ]; then
        echo '{"error": "unit and identifier are mutually exclusive"}'
        exit 1
      fi
      for value_name in lines max_chars max_line_chars; do
        value_var="''${value_name}_raw"
        value="''${!value_var}"
        if ! [[ "$value" =~ ^[0-9]+$ ]] || [ "$value" -lt 1 ]; then
          ${pkgs.jq}/bin/jq -n --arg field "$value_name" --arg value "$value" '{"error": "invalid numeric parameter", "field": $field, "value": $value}'
          exit 1
        fi
      done

      lines_requested="$lines_raw"
      line_limit_clamped=false
      char_limit_clamped=false
      max_line_chars_clamped=false
      if [ "$lines_raw" -gt 100 ]; then
        lines=100
        line_limit_clamped=true
      else
        lines="$lines_raw"
      fi
      if [ "$max_chars_raw" -gt 100000 ]; then
        max_chars=100000
        char_limit_clamped=true
      else
        max_chars="$max_chars_raw"
      fi
      if [ "$max_line_chars_raw" -gt 10000 ]; then
        max_line_chars=10000
        max_line_chars_clamped=true
      else
        max_line_chars="$max_line_chars_raw"
      fi

      # Build journalctl command
      if [ -n "$unit" ]; then
        args=("-u" "$unit")
      else
        args=("-t" "$identifier")
      fi
      args+=("-n" "$lines" "--no-pager" "-o" "short-iso")
      if [ -n "$since" ]; then
        args+=("--since" "$since")
      fi
      if [ -n "$until" ]; then
        args+=("--until" "$until")
      fi
      if [ -n "$grep_pattern" ]; then
        args+=("--grep" "$grep_pattern")
      fi

      raw_file=$(${pkgs.coreutils}/bin/mktemp)
      trap 'rm -f "$raw_file"' EXIT
      ${pkgs.systemd}/bin/journalctl "''${args[@]}" > "$raw_file" 2>&1 || true
      ${pkgs.python3}/bin/python3 ${sanitizeJournalOutput} "$raw_file" "$lines_requested" "$lines" "$max_chars" "$max_line_chars" "$line_limit_clamped" "$char_limit_clamped" "$max_line_chars_clamped"
    '');

    # Service management operations (debug capability)
    # Actions: restart, start, stop, failed, status, list
    # On darwin: maps to launchctl operations
    systemd = pkgs.writeShellScript "handler-systemd" (if isDarwin then ''
      set -euo pipefail

      input=$(${pkgs.coreutils}/bin/cat)
      if ! echo "$input" | ${pkgs.jq}/bin/jq empty 2>/dev/null; then
        echo '{"error": "invalid request: expected JSON body, e.g. {\"action\":\"status\",\"unit\":\"nginx\"}"}'
        exit 1
      fi
      action=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.action // "restart"')

      # Helper: validate service label
      validate_label() {
        if [ -z "$1" ]; then
          echo '{"error": "unit parameter required"}'
          exit 1
        fi
        if ! echo "$1" | ${pkgs.gnugrep}/bin/grep -qE '^[a-zA-Z0-9@_./-]+$'; then
          echo '{"error": "invalid unit name"}'
          exit 1
        fi
      }

      # Helper: resolve a short name to a launchd label.
      # Tries the name as given, then scans loaded labels for a suffix match
      # treating '-' and '.' as interchangeable (fort-provider matches
      # network.gisi.fort.provider).
      resolve_label() {
        local name="$1"
        if /bin/launchctl print "system/$name" >/dev/null 2>&1; then
          echo "$name"
          return
        fi
        local pattern
        pattern=$(echo "$name" | ${pkgs.gnused}/bin/sed 's/[-.]/[-.]/g')
        local match
        match=$(/bin/launchctl list 2>/dev/null | ${pkgs.gawk}/bin/awk 'NR>1 {print $3}' \
          | ${pkgs.gnugrep}/bin/grep -E -- "(^|\.)''${pattern}$" | ${pkgs.coreutils}/bin/head -1)
        if [ -n "$match" ]; then
          echo "$match"
        else
          echo "$name"  # fall through; launchctl will report the error
        fi
      }

      case "$action" in
        restart)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')
          validate_label "$unit"
          label=$(resolve_label "$unit")
          plist="/Library/LaunchDaemons/$label.plist"

          # Prefer bootout + bootstrap: unlike kickstart -k, this clears
          # launchd's spawn throttle (q-d9b7ef7b — a service that crashed
          # recently, e.g. right after reboot, refuses kickstart until the
          # throttle interval expires).
          if [ -f "$plist" ]; then
            /bin/launchctl bootout "system/$label" 2>/dev/null || true
            if output=$(/bin/launchctl bootstrap system "$plist" 2>&1); then
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" \
                '{"status": "restarted", "unit": $unit, "label": $label, "method": "bootstrap"}'
            else
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" --arg error "$output" \
                '{"error": "restart failed", "unit": $unit, "label": $label, "details": $error}'
              exit 1
            fi
          elif output=$(/bin/launchctl kickstart -k "system/$label" 2>&1); then
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" \
              '{"status": "restarted", "unit": $unit, "label": $label, "method": "kickstart"}'
          else
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" --arg error "$output" \
              '{"error": "restart failed", "unit": $unit, "label": $label, "details": $error}'
            exit 1
          fi
          ;;

        start)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')
          validate_label "$unit"
          label=$(resolve_label "$unit")
          plist="/Library/LaunchDaemons/$label.plist"

          # If the service isn't loaded (e.g. after a stop via bootout),
          # bootstrap it from its plist; otherwise kickstart it.
          if ! /bin/launchctl print "system/$label" >/dev/null 2>&1 && [ -f "$plist" ]; then
            if output=$(/bin/launchctl bootstrap system "$plist" 2>&1); then
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" \
                '{"status": "started", "unit": $unit, "label": $label, "method": "bootstrap"}'
            else
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" --arg error "$output" \
                '{"error": "start failed", "unit": $unit, "label": $label, "details": $error}'
              exit 1
            fi
          elif output=$(/bin/launchctl kickstart "system/$label" 2>&1); then
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" \
              '{"status": "started", "unit": $unit, "label": $label, "method": "kickstart"}'
          else
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" --arg error "$output" \
              '{"error": "start failed", "unit": $unit, "label": $label, "details": $error}'
            exit 1
          fi
          ;;

        stop)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')
          validate_label "$unit"
          label=$(resolve_label "$unit")

          # bootout actually unloads the job — SIGTERM alone is undone by
          # KeepAlive, which immediately respawns the process.
          if output=$(/bin/launchctl bootout "system/$label" 2>&1); then
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" \
              '{"status": "stopped", "unit": $unit, "label": $label, "method": "bootout"}'
          elif output=$(/bin/launchctl kill SIGTERM "system/$label" 2>&1); then
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" \
              '{"status": "stopped", "unit": $unit, "label": $label, "method": "sigterm"}'
          else
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg label "$label" --arg error "$output" \
              '{"error": "stop failed", "unit": $unit, "label": $label, "details": $error}'
            exit 1
          fi
          ;;

        failed)
          # List services in error state
          # launchctl list shows PID, exit status, label — non-zero exit = failed
          failed_services=$(/bin/launchctl list 2>/dev/null | ${pkgs.gawk}/bin/awk '$2 != 0 && $2 != "-" {print $3}')
          if [ -z "$failed_services" ]; then
            echo '{"units": [], "count": 0}'
          else
            echo "$failed_services" | ${pkgs.jq}/bin/jq -R -s -c \
              'split("\n") | map(select(length > 0)) | {units: ., count: length}'
          fi
          ;;

        status)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')
          validate_label "$unit"
          label=$(resolve_label "$unit")

          # Get service info from launchctl list
          if info=$(/bin/launchctl list "$label" 2>&1); then
            pid=$(echo "$info" | ${pkgs.gnugrep}/bin/grep '"PID"' | ${pkgs.gawk}/bin/awk '{print $NF}' | tr -d ';' || echo "0")
            exit_status=$(echo "$info" | ${pkgs.gnugrep}/bin/grep '"LastExitStatus"' | ${pkgs.gawk}/bin/awk '{print $NF}' | tr -d ';' || echo "0")
            if [ -n "$pid" ] && [ "$pid" != "0" ]; then
              active="active"
              sub="running"
            else
              active="inactive"
              sub="dead"
            fi
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg active "$active" --arg sub "$sub" --arg load "loaded" \
              '{unit: $unit, active: $active, sub: $sub, load: $load}'
          else
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg error "$info" \
              '{"error": "status failed", "unit": $unit, "details": $error}'
            exit 1
          fi
          ;;

        list)
          pattern=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.pattern // "*"')

          # List launchd services matching pattern
          services=$(/bin/launchctl list 2>/dev/null | ${pkgs.gawk}/bin/awk 'NR>1 {print $3}' | ${pkgs.gnugrep}/bin/grep -E "$pattern" || true)
          if [ -z "$services" ]; then
            echo '{"units": [], "count": 0}'
          else
            echo "$services" | ${pkgs.jq}/bin/jq -R -s -c \
              'split("\n") | map(select(length > 0)) | {units: ., count: length}'
          fi
          ;;

        *)
          ${pkgs.jq}/bin/jq -n --arg action "$action" \
            '{"error": "unknown action", "action": $action, "valid_actions": ["start", "restart", "stop", "failed", "status", "list"]}'
          exit 1
          ;;
      esac
    '' else ''
      set -euo pipefail

      input=$(${pkgs.coreutils}/bin/cat)
      if ! echo "$input" | ${pkgs.jq}/bin/jq empty 2>/dev/null; then
        echo '{"error": "invalid request: expected JSON body, e.g. {\"action\":\"status\",\"unit\":\"nginx\"}"}'
        exit 1
      fi
      action=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.action // "restart"')

      case "$action" in
        restart)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')
          delay=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.delay // 0')

          if [ -z "$unit" ]; then
            echo '{"error": "unit parameter required"}'
            exit 1
          fi

          # Basic validation: unit name should be reasonable
          if ! echo "$unit" | ${pkgs.gnugrep}/bin/grep -qE '^[a-zA-Z0-9@_.-]+$'; then
            echo '{"error": "invalid unit name"}'
            exit 1
          fi

          # Validate delay is a number
          if ! echo "$delay" | ${pkgs.gnugrep}/bin/grep -qE '^[0-9]+$'; then
            echo '{"error": "delay must be a non-negative integer (seconds)"}'
            exit 1
          fi

          if [ "$delay" -gt 0 ]; then
            # Schedule restart in the future - allows response to complete first
            if output=$(${pkgs.systemd}/bin/systemd-run --on-active="''${delay}s" \
                ${pkgs.systemd}/bin/systemctl restart "$unit" 2>&1); then
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" --argjson delay "$delay" \
                '{"status": "scheduled", "unit": $unit, "delay_seconds": $delay}'
            else
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg error "$output" \
                '{"error": "schedule failed", "unit": $unit, "details": $error}'
              exit 1
            fi
          else
            # Immediate restart
            if output=$(${pkgs.systemd}/bin/systemctl restart "$unit" 2>&1); then
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" '{"status": "restarted", "unit": $unit}'
            else
              ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg error "$output" \
                '{"error": "restart failed", "unit": $unit, "details": $error}'
              exit 1
            fi
          fi
          ;;

        start)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')

          if [ -z "$unit" ]; then
            echo '{"error": "unit parameter required"}'
            exit 1
          fi

          if ! echo "$unit" | ${pkgs.gnugrep}/bin/grep -qE '^[a-zA-Z0-9@_.-]+$'; then
            echo '{"error": "invalid unit name"}'
            exit 1
          fi

          if output=$(${pkgs.systemd}/bin/systemctl start "$unit" 2>&1); then
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" '{"status": "started", "unit": $unit}'
          else
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg error "$output" \
              '{"error": "start failed", "unit": $unit, "details": $error}'
            exit 1
          fi
          ;;

        stop)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')

          if [ -z "$unit" ]; then
            echo '{"error": "unit parameter required"}'
            exit 1
          fi

          if ! echo "$unit" | ${pkgs.gnugrep}/bin/grep -qE '^[a-zA-Z0-9@_.-]+$'; then
            echo '{"error": "invalid unit name"}'
            exit 1
          fi

          if output=$(${pkgs.systemd}/bin/systemctl stop "$unit" 2>&1); then
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" '{"status": "stopped", "unit": $unit}'
          else
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg error "$output" \
              '{"error": "stop failed", "unit": $unit, "details": $error}'
            exit 1
          fi
          ;;

        failed)
          # List failed units
          failed_units=$(${pkgs.systemd}/bin/systemctl --failed --no-legend --plain | ${pkgs.gawk}/bin/awk '{print $1}')
          if [ -z "$failed_units" ]; then
            echo '{"units": [], "count": 0}'
          else
            echo "$failed_units" | ${pkgs.jq}/bin/jq -R -s -c \
              'split("\n") | map(select(length > 0)) | {units: ., count: length}'
          fi
          ;;

        status)
          unit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.unit // empty')

          if [ -z "$unit" ]; then
            echo '{"error": "unit parameter required"}'
            exit 1
          fi

          if ! echo "$unit" | ${pkgs.gnugrep}/bin/grep -qE '^[a-zA-Z0-9@_.-]+$'; then
            echo '{"error": "invalid unit name"}'
            exit 1
          fi

          # Get unit properties as JSON
          if props=$(${pkgs.systemd}/bin/systemctl show "$unit" --no-pager 2>&1); then
            active=$(echo "$props" | ${pkgs.gnugrep}/bin/grep '^ActiveState=' | cut -d= -f2)
            sub=$(echo "$props" | ${pkgs.gnugrep}/bin/grep '^SubState=' | cut -d= -f2)
            load=$(echo "$props" | ${pkgs.gnugrep}/bin/grep '^LoadState=' | cut -d= -f2)
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg active "$active" --arg sub "$sub" --arg load "$load" \
              '{unit: $unit, active: $active, sub: $sub, load: $load}'
          else
            ${pkgs.jq}/bin/jq -n --arg unit "$unit" --arg error "$props" \
              '{"error": "status failed", "unit": $unit, "details": $error}'
            exit 1
          fi
          ;;

        list)
          pattern=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.pattern // "*"')

          # List units matching pattern
          units=$(${pkgs.systemd}/bin/systemctl list-units --no-legend --plain "$pattern" 2>/dev/null | ${pkgs.gawk}/bin/awk '{print $1}')
          if [ -z "$units" ]; then
            echo '{"units": [], "count": 0}'
          else
            echo "$units" | ${pkgs.jq}/bin/jq -R -s -c \
              'split("\n") | map(select(length > 0)) | {units: ., count: length}'
          fi
          ;;

        *)
          ${pkgs.jq}/bin/jq -n --arg action "$action" \
            '{"error": "unknown action", "action": $action, "valid_actions": ["start", "restart", "stop", "failed", "status", "list"]}'
          exit 1
          ;;
      esac
    '');

    # Read file contents with optional offset and limit
    # Useful for remote diagnostics without SSH access
    read-file = pkgs.writeShellScript "handler-read-file" ''
      set -euo pipefail

      input=$(${pkgs.coreutils}/bin/cat)
      if ! echo "$input" | ${pkgs.jq}/bin/jq empty 2>/dev/null; then
        echo '{"error": "invalid request: expected JSON body, e.g. {\"path\":\"/var/log/nginx\"}"}'
        exit 1
      fi
      file_path=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.path // empty')
      offset=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.offset // 0')
      limit=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.limit // 1000')

      if [ -z "$file_path" ]; then
        ${pkgs.jq}/bin/jq -n '{"error": "path parameter required"}'
        exit 1
      fi

      # Security: block sensitive paths
      case "$file_path" in
        /etc/shadow*|/etc/gshadow*|*/.ssh/id_*|*/private*key*|*.age)
          ${pkgs.jq}/bin/jq -n --arg path "$file_path" '{"error": "access denied", "path": $path}'
          exit 1
          ;;
      esac

      # Validate offset and limit are numbers
      if ! echo "$offset" | ${pkgs.gnugrep}/bin/grep -qE '^[0-9]+$'; then
        ${pkgs.jq}/bin/jq -n '{"error": "offset must be a non-negative integer"}'
        exit 1
      fi
      if ! echo "$limit" | ${pkgs.gnugrep}/bin/grep -qE '^[0-9]+$'; then
        ${pkgs.jq}/bin/jq -n '{"error": "limit must be a non-negative integer"}'
        exit 1
      fi

      # Cap limit at 10000 lines
      if [ "$limit" -gt 10000 ]; then
        limit=10000
      fi

      if [ ! -e "$file_path" ]; then
        ${pkgs.jq}/bin/jq -n --arg path "$file_path" '{"error": "file not found", "path": $path}'
        exit 1
      fi

      if [ -d "$file_path" ]; then
        # Directory listing
        if listing=$(${pkgs.coreutils}/bin/ls -la "$file_path" 2>&1); then
          ${pkgs.jq}/bin/jq -n --arg path "$file_path" --arg listing "$listing" \
            '{"path": $path, "type": "directory", "listing": $listing}'
        else
          ${pkgs.jq}/bin/jq -n --arg path "$file_path" --arg error "$listing" \
            '{"error": "ls failed", "path": $path, "details": $error}'
          exit 1
        fi
      else
        # File content with offset and limit
        total_lines=$(${pkgs.coreutils}/bin/wc -l < "$file_path" 2>/dev/null || echo "0")
        start_line=$((offset + 1))

        if content=$(${pkgs.coreutils}/bin/tail -n "+$start_line" "$file_path" 2>&1 | ${pkgs.coreutils}/bin/head -n "$limit"); then
          ${pkgs.jq}/bin/jq -n \
            --arg path "$file_path" \
            --arg content "$content" \
            --argjson offset "$offset" \
            --argjson limit "$limit" \
            --argjson total_lines "$total_lines" \
            '{"path": $path, "type": "file", "content": $content, "offset": $offset, "limit": $limit, "total_lines": $total_lines}'
        else
          ${pkgs.jq}/bin/jq -n --arg path "$file_path" --arg error "$content" \
            '{"error": "read failed", "path": $path, "details": $error}'
          exit 1
        fi
      fi
    '';

    # Refresh a capability: re-invoke handler and re-deliver to all subscribers
    # Used to push updated state after source data changes (e.g., CI builds new artifact)
    # Optional force parameter omits cached responses, requiring handler to recompute
    refresh = pkgs.writeShellScript "handler-refresh" ''
      set -euo pipefail

      input=$(${pkgs.coreutils}/bin/cat)
      if ! echo "$input" | ${pkgs.jq}/bin/jq empty 2>/dev/null; then
        echo '{"error": "invalid request: expected JSON body, e.g. {\"capability\":\"oidc-register\"}"}'
        exit 1
      fi
      capability=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.capability // empty')
      force=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.force // false')

      if [ -z "$capability" ]; then
        ${pkgs.jq}/bin/jq -n '{"error": "capability parameter required"}'
        exit 1
      fi

      # Check if we provide this capability (excluding mandatory ones that don't have state)
      if ! ${pkgs.jq}/bin/jq -e --arg cap "$capability" '.[$cap]' /etc/fort/capabilities.json > /dev/null 2>&1; then
        ${pkgs.jq}/bin/jq -n --arg cap "$capability" '{"error": "not a provider for this capability", "capability": $cap}'
        exit 1
      fi

      # Build trigger command
      if [ "$force" = "true" ]; then
        ${fortProvider}/bin/fort-provider --trigger "$capability" --force
        status="force-refreshed"
      else
        ${fortProvider}/bin/fort-provider --trigger "$capability"
        status="refreshed"
      fi

      ${pkgs.jq}/bin/jq -n --arg status "$status" --arg cap "$capability" \
        '{status: $status, capability: $cap}'
    '';

    # Force immediate retry of needs by resetting fulfillment state
    # Optional pattern parameter filters which needs to reset (substring match)
    # If pattern is empty/missing, resets ALL needs
    force-nag = pkgs.writeShellScript "handler-force-nag" ''
      set -euo pipefail

      STATE_FILE="/var/lib/fort/fulfillment-state.json"
      input=$(${pkgs.coreutils}/bin/cat)
      if ! echo "$input" | ${pkgs.jq}/bin/jq empty 2>/dev/null; then
        echo '{"error": "invalid request: expected JSON body, e.g. {\"pattern\":\"oidc\"} or {}"}'
        exit 1
      fi
      pattern=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.pattern // empty')

      if [ ! -f "$STATE_FILE" ]; then
        ${pkgs.jq}/bin/jq -n '{"status": "no_state", "message": "No fulfillment state exists"}'
        exit 0
      fi

      # Count current entries
      before_count=$(${pkgs.jq}/bin/jq 'length' "$STATE_FILE")

      if [ -z "$pattern" ]; then
        # Reset everything - truncate to empty object
        echo '{}' > "$STATE_FILE"
        reset_count=$before_count
        reset_keys="all"
      else
        # Reset only matching keys (by substring match on key name)
        reset_keys=$(${pkgs.jq}/bin/jq -r --arg p "$pattern" \
          'keys[] | select(contains($p))' "$STATE_FILE" | tr '\n' ',' | sed 's/,$//')

        ${pkgs.jq}/bin/jq --arg p "$pattern" \
          'with_entries(select(.key | contains($p) | not))' \
          "$STATE_FILE" > "$STATE_FILE.tmp" && mv "$STATE_FILE.tmp" "$STATE_FILE"

        after_count=$(${pkgs.jq}/bin/jq 'length' "$STATE_FILE")
        reset_count=$((before_count - after_count))
      fi

      # Restart fort-consumer to trigger immediate retry
      ${if isDarwin then
        "/bin/launchctl kickstart -k system/network.gisi.fort.consumer 2>/dev/null || true"
      else
        "${pkgs.systemd}/bin/systemctl restart fort-consumer 2>/dev/null || true"
      }

      ${pkgs.jq}/bin/jq -n \
        --arg pattern "$pattern" \
        --argjson reset_count "$reset_count" \
        --arg reset_keys "$reset_keys" \
        '{status: "reset", pattern: (if $pattern == "" then "all" else $pattern end), reset_count: $reset_count, reset_keys: $reset_keys, consumer_restarted: true}'
    '';
}
