name: Flake Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4

      - name: Check root flake
        run: nix flake check --no-build
        env:
          NIX_CONFIG: "warn-dirty = false"

      - name: Check host flakes
        run: |
          for host_dir in ./clusters/bedlam/hosts/*/; do
            host=$(basename "$host_dir")
            echo "::group::Checking host: $host"
            nix flake check "$host_dir" --no-build
            echo "::endgroup::"
          done
        env:
          NIX_CONFIG: "warn-dirty = false"

      - name: Check device flakes
        run: |
          for device_dir in ./clusters/bedlam/devices/*/; do
            device=$(basename "$device_dir")
            echo "::group::Checking device: $device"
            nix flake check "$device_dir" --no-build
            echo "::endgroup::"
          done
        env:
          NIX_CONFIG: "warn-dirty = false"
