# cal-sync: compose vdirsyncer's config from the static base (written at boot
# by vdirsyncer-config, holds the secrets) plus one read-only Google pair per
# token calroom has saved, discover new pairs, sync, then render the agenda
# Kes and familiar-ui read. Run by the 15-minute timer and by calroom's
# "Sync now"; a flock keeps the two from overlapping.
#
# Env (defaults match the dev-sandbox layout on ratched):
#   VD_HOME   dev's home                    (/home/dev)
#   VD_DATA   token directory root          (/var/lib/vdirsyncer)
set -euo pipefail

home="${VD_HOME:-/home/dev}"
data="${VD_DATA:-/var/lib/vdirsyncer}"
conf_dir="$home/.config/vdirsyncer"
share="$home/.local/share/vdirsyncer"
base="$conf_dir/config.base"
creds="$conf_dir/google-client.env"
cfg="$conf_dir/config"

mkdir -p "$share/status" "$share/google"
exec 9>"$share/.sync.lock"
flock -w 900 9

if [[ ! -r "$base" || ! -r "$creds" ]]; then
  echo "cal-sync: $base or $creds missing (vdirsyncer-config not run yet?)" >&2
  exit 1
fi
# shellcheck disable=SC1090
. "$creds"

tmp="$(mktemp "$conf_dir/.config.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
{
  cat "$base"
  for tok in "$data"/tokens/*.json; do
    [[ -e "$tok" ]] || continue
    email="$(basename "$tok" .json)"
    slug="$(printf %s "$email" | tr -c 'a-z0-9' '_')"
    mkdir -p "$share/google/$email"
    cat <<EOF

# --- generated by cal-sync for $email (calroom) ---
[pair g_$slug]
a = "g_${slug}_remote"
b = "g_${slug}_local"
collections = ["from a"]
metadata = ["color", "displayname"]
conflict_resolution = "a wins"
partial_sync = "revert"

[storage g_${slug}_remote]
type = "google_calendar"
token_file = "$tok"
client_id = "$CLIENT_ID"
client_secret = "$CLIENT_SECRET"
read_only = true

[storage g_${slug}_local]
type = "filesystem"
path = "$share/google/$email/"
fileext = ".ics"
EOF
  done
} >"$tmp"
chmod 600 "$tmp"
mv "$tmp" "$cfg"
trap - EXIT

rc=0
mapfile -t all_pairs < <(sed -n 's/^\[pair \([^]]*\)\]$/\1/p' "$cfg")
# New pairs need one discovery pass before they can sync. vdirsyncer asks
# before creating each local collection; the answer is always yes.
for pair in "${all_pairs[@]}"; do
  if [[ ! -e "$share/status/$pair.collections" && ! -d "$share/status/$pair" ]]; then
    if [[ "$pair" == google_calendar && ! -e "$data/token" ]]; then continue; fi
    echo "discovering $pair"
    { yes || true; } | vdirsyncer discover "$pair" || { echo "discover $pair failed" >&2; rc=1; }
  fi
done

pairs=()
for pair in "${all_pairs[@]}"; do
  if [[ "$pair" == google_calendar && ! -e "$data/token" ]]; then continue; fi
  pairs+=("$pair")
done

# One broken account must not stall the rest: sync pair by pair.
for pair in "${pairs[@]}"; do
  vdirsyncer sync "$pair" || { echo "sync $pair failed" >&2; rc=1; }
done
vdirsyncer metasync "${pairs[@]}" >/dev/null 2>&1 || true
touch "$share/.last_sync"

# Agenda: next two weeks, every calendar khal knows, plus a name map so
# readers can show "Family" instead of a collection id.
agenda="$share/agenda.json"
names="$(
  for d in "$share"/calendars/* "$share"/google/*/* "$share"/radicale/* "$share"/radicale-family/*; do
    [[ -d "$d" ]] || continue
    id="$(basename "$d")"
    src="google"
    case "$d" in
      "$share"/radicale/*) src="radicale:kevin" ;;
      "$share"/radicale-family/*) src="radicale:family" ;;
      "$share"/calendars/*) src="google:work" ;;
      "$share"/google/*) src="google:$(basename "$(dirname "$d")")" ;;
    esac
    name="$id"
    [[ -s "$d/displayname" ]] && name="$(head -c 200 "$d/displayname")"
    jq -cn --arg id "$id" --arg name "$name" --arg src "$src" '{id:$id,name:$name,source:$src}'
  done | jq -cs '.'
)"
if khal list --json title --json start-long --json end-long --json all-day \
  --json calendar --json location today 14d >"$agenda.raw" 2>"$agenda.err"; then
  jq -s --argjson cals "$names" '{
      v: 1,
      generatedAt: (now | todate),
      tz: "America/Chicago",
      calendars: $cals,
      events: [ (add // [])[] | {
        title: .title,
        start: ."start-long",
        end: ."end-long",
        allDay: (."all-day" == "True"),
        calendar: .calendar,
        location: .location
      } ]
    }' "$agenda.raw" >"$agenda.tmp"
  chmod 600 "$agenda.tmp"
  mv "$agenda.tmp" "$agenda"
else
  echo "khal list failed: $(head -c 500 "$agenda.err")" >&2
  rc=1
fi
rm -f "$agenda.raw" "$agenda.err"
exit "$rc"
