package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

// Syncer pulls every account with mbsync on an interval, one account at a
// time. Each run mints a fresh access token, writes it beside a generated
// mbsyncrc (both 0600, both in our private state dir) and lets mbsync's
// PassCmd cat it back. mbsync speaks XOAUTH2 via the cyrus-sasl plugin.
type Syncer struct {
	Store    *Store
	Google   *Google
	Mbsync   string
	MailRoot string // /var/lib/mail/maildir
	StateDir string // /var/lib/mailroom
	Interval time.Duration
	Timeout  time.Duration

	kick chan string
}

func (s *Syncer) Kick(email string) {
	select {
	case s.kick <- email:
	default: // a sync is already queued; it will cover this
	}
}

func (s *Syncer) Run(ctx context.Context) {
	t := time.NewTicker(s.Interval)
	defer t.Stop()
	s.syncAll(ctx)
	for {
		select {
		case <-ctx.Done():
			return
		case <-t.C:
			s.syncAll(ctx)
		case email := <-s.kick:
			if email == "" {
				s.syncAll(ctx)
			} else {
				s.syncOne(ctx, email)
			}
		}
	}
}

func (s *Syncer) syncAll(ctx context.Context) {
	for _, a := range s.Store.List() {
		if ctx.Err() != nil {
			return
		}
		s.syncOne(ctx, a.Email)
	}
}

func (s *Syncer) syncOne(ctx context.Context, email string) {
	a, ok := s.Store.Get(email)
	if !ok || a.NeedsReauth {
		return
	}
	_ = s.Store.Update(email, func(a *Account) { a.Syncing = true })
	out, err := s.run(ctx, a)
	_ = s.Store.Update(email, func(a *Account) {
		a.Syncing = false
		a.LastSync = time.Now().UTC()
		a.LastOutput = tail(out, 4000)
		if err != nil {
			a.LastError = err.Error()
			if errors.Is(err, ErrReauth) {
				a.NeedsReauth = true
			}
		} else {
			a.LastError = ""
			a.LastOK = a.LastSync
		}
	})
	if err != nil {
		log.Printf("sync %s: %v", email, err)
	} else {
		log.Printf("sync %s: ok", email)
	}
}

func tail(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return "…" + s[len(s)-n:]
}

func (s *Syncer) run(ctx context.Context, a Account) (string, error) {
	tok, err := s.Google.AccessToken(a)
	if err != nil {
		return "", err
	}
	id := slug(a.Email)
	runDir := filepath.Join(s.StateDir, "run")
	if err := os.MkdirAll(runDir, 0o700); err != nil {
		return "", err
	}
	tokFile := filepath.Join(runDir, id+".token")
	if err := os.WriteFile(tokFile, []byte(tok), 0o600); err != nil {
		return "", err
	}
	defer os.Remove(tokFile)

	syncState := filepath.Join(s.StateDir, "syncstate", id) + "/"
	if err := os.MkdirAll(syncState, 0o700); err != nil {
		return "", err
	}
	maildir := filepath.Join(s.MailRoot, a.Email) + "/"
	if err := os.MkdirAll(maildir, 0o700); err != nil {
		return "", err
	}
	rc, err := renderMbsyncrc(mbsyncParams{
		ID: id, Email: a.Email, TokenFile: tokFile,
		Maildir: maildir, SyncState: syncState, Archive: a.Archive,
	})
	if err != nil {
		return "", err
	}
	rcFile := filepath.Join(runDir, id+".mbsyncrc")
	if err := os.WriteFile(rcFile, []byte(rc), 0o600); err != nil {
		return "", err
	}

	cctx, cancel := context.WithTimeout(ctx, s.Timeout)
	defer cancel()
	cmd := exec.CommandContext(cctx, s.Mbsync, "-c", rcFile, "-a")
	var buf bytes.Buffer
	cmd.Stdout, cmd.Stderr = &buf, &buf
	err = cmd.Run()
	out := buf.String()
	if err != nil {
		if strings.Contains(out, "AUTHENTICATE") || strings.Contains(out, "Invalid credentials") {
			// Token was fresh; this smells like IMAP disabled or a Workspace
			// policy, not an expired grant. Surface it verbatim.
			return out, fmt.Errorf("IMAP login refused: %s", firstLine(out))
		}
		return out, fmt.Errorf("mbsync: %v: %s", err, firstLine(out))
	}
	return out, nil
}

func firstLine(s string) string {
	for _, l := range strings.Split(s, "\n") {
		l = strings.TrimSpace(l)
		if l != "" && !strings.HasPrefix(l, "Notice:") {
			return l
		}
	}
	return ""
}

type mbsyncParams struct {
	ID, Email, TokenFile, Maildir, SyncState string
	Archive                                  bool
}

// Policy per folder:
//
//	INBOX   two-way. Archiving/deleting locally removes the INBOX label in
//	        Gmail (expunge from INBOX == archive). Upstream archiving drops
//	        it from the local INBOX.
//	Sent    pull-only, never expunged locally.
//	Archive [Gmail]/All Mail, pull-only, never expunged locally: the copy
//	        Google can't take back. Opt-in per account (it can be large).
var mbsyncTmpl = template.Must(template.New("rc").Parse(`# generated by mailroom; do not edit
IMAPAccount {{.ID}}
Host imap.gmail.com
Port 993
TLSType IMAPS
User {{.Email}}
AuthMechs XOAUTH2
PassCmd "cat {{.TokenFile}}"
CertificateFile /etc/ssl/certs/ca-certificates.crt
Timeout 120
PipelineDepth 50

IMAPStore {{.ID}}-far
Account {{.ID}}

MaildirStore {{.ID}}-near
Path {{.Maildir}}
Inbox {{.Maildir}}INBOX
SubFolders Verbatim

Channel {{.ID}}-inbox
Far :{{.ID}}-far:INBOX
Near :{{.ID}}-near:INBOX
Create Near
Sync Full
Expunge Both
CopyArrivalDate yes
SyncState {{.SyncState}}

Channel {{.ID}}-sent
Far ":{{.ID}}-far:[Gmail]/Sent Mail"
Near :{{.ID}}-near:Sent
Create Near
Sync Pull New Flags
Expunge None
CopyArrivalDate yes
SyncState {{.SyncState}}
{{if .Archive}}
Channel {{.ID}}-archive
Far ":{{.ID}}-far:[Gmail]/All Mail"
Near :{{.ID}}-near:Archive
Create Near
Sync Pull New Flags
Expunge None
CopyArrivalDate yes
SyncState {{.SyncState}}
{{end}}`))

func renderMbsyncrc(p mbsyncParams) (string, error) {
	for _, v := range []string{p.ID, p.Email, p.TokenFile, p.Maildir, p.SyncState} {
		if strings.ContainsAny(v, "\"\n\r ") {
			return "", fmt.Errorf("unsafe value in mbsync config: %q", v)
		}
	}
	var b bytes.Buffer
	err := mbsyncTmpl.Execute(&b, p)
	return b.String(), err
}
