#!/usr/bin/env bash
# fn-66f9: Automated sops rekey with derived .sops.yaml
#
# Usage: rekey.sh              — full derivation + rekey all changed files
#        rekey.sh <path>       — rekey single file (skip derivation, use existing .sops.yaml)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# sops looks for age keys at ~/.config/sops/age/keys.txt by default;
# our dev-sandbox key lives at ~/.config/age/keys.txt
export SOPS_AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-${HOME}/.config/age/keys.txt}"

# Resolve cluster paths
cluster_name=$(nix eval --raw --impure --expr '(import ./common/cluster-context.nix { }).clusterName')
hosts_root="./clusters/${cluster_name}/hosts"
devices_root="./clusters/${cluster_name}/devices"

# --- Single-file mode ---
if [[ -n "${1:-}" ]]; then
  echo "[rekey] Updating keys for $1"
  sops updatekeys -y "$1"
  exit 0
fi

# --- Full derivation mode ---

echo "[rekey] Collecting principal keys..."

# Get principals with secrets role, output as JSON array of {name, publicKey}
principals_json=$(nix eval --impure --json --expr '
  let
    cluster = import ./common/cluster-context.nix { };
    settings = cluster.manifest.fortConfig.settings;
    principals = settings.principals;
    names = builtins.attrNames principals;
    withSecrets = builtins.filter (n:
      builtins.elem "secrets" (principals.${n}.roles or [])
    ) names;
  in map (n: { name = n; publicKey = principals.${n}.publicKey; }) withSecrets
')

# Convert principal keys to age keys
declare -A principal_age_keys
while IFS=$'\t' read -r name pubkey; do
  if [[ "$pubkey" == age1* ]]; then
    principal_age_keys["$name"]="$pubkey"
  elif [[ "$pubkey" == ssh-* ]]; then
    age_key=$(echo "$pubkey" | ssh-to-age 2>/dev/null)
    principal_age_keys["$name"]="$age_key"
  else
    echo "[rekey] WARNING: Unknown key format for principal $name, skipping" >&2
  fi
done < <(echo "$principals_json" | jq -r '.[] | [.name, .publicKey] | @tsv')

echo "[rekey] Found ${#principal_age_keys[@]} principals with secrets role"

# --- Walk hosts in parallel ---
echo "[rekey] Evaluating sops.secrets across all hosts..."

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

host_count=0
for host_dir in "$hosts_root"/*/; do
  [[ -d "$host_dir" ]] || continue
  host_name=$(basename "$host_dir")
  host_count=$((host_count + 1))

  (
    # Eval sops.secrets for this host
    secrets_json=$(nix eval "./${hosts_root}/${host_name}#nixosConfigurations.${host_name}.config.sops.secrets" --json 2>/dev/null || echo "{}")

    # Extract unique sopsFile paths (strip nix store prefix)
    sops_files=$(echo "$secrets_json" | jq -r '
      [.[] | .sopsFile // empty]
      | unique
      | .[]
    ' | while read -r store_path; do
      # Strip everything up to and including -source/
      echo "$store_path" | sed 's|.*/[^/]*-source/||'
    done | sort -u)

    if [[ -z "$sops_files" ]]; then
      exit 0
    fi

    # Get device UUID from host manifest
    device_uuid=$(nix eval --raw --impure --expr "(import ./${hosts_root}/${host_name}/manifest.nix).device")

    # Get device pubkey and convert to age
    device_pubkey=$(nix eval --raw --impure --expr "(import ./${devices_root}/${device_uuid}/manifest.nix).pubkey")
    device_age_key=$(echo "$device_pubkey" | ssh-to-age 2>/dev/null)

    # Write results
    echo "$sops_files" | while read -r sf; do
      [[ -n "$sf" ]] || continue
      echo -e "${sf}\t${host_name}\t${device_age_key}" >> "$tmpdir/mappings.tsv"
    done
  ) &
done

echo "[rekey] Waiting for ${host_count} host evaluations..."
wait
echo "[rekey] Host evaluations complete"

if [[ ! -f "$tmpdir/mappings.tsv" ]]; then
  echo "[rekey] No sops secrets found across any host"
  exit 0
fi

# --- Build recipient map ---
# For each sopsFile: principal keys + device keys of all consuming hosts
declare -A file_device_keys
while IFS=$'\t' read -r sops_file host_name device_age_key; do
  existing="${file_device_keys[$sops_file]:-}"
  if [[ -n "$existing" ]]; then
    # Append only if not already present
    if [[ "$existing" != *"$device_age_key"* ]]; then
      file_device_keys["$sops_file"]="${existing} ${host_name}=${device_age_key}"
    fi
  else
    file_device_keys["$sops_file"]="${host_name}=${device_age_key}"
  fi
done < "$tmpdir/mappings.tsv"

# --- Generate .sops.yaml ---
echo "[rekey] Generating .sops.yaml..."

sops_yaml="$tmpdir/sops.yaml"
cat > "$sops_yaml" <<'HEADER'
# GENERATED by `just rekey` — do not edit manually.
# See scripts/rekey.sh (fn-66f9) for the generation logic.
creation_rules:
HEADER

# Sort sopsFiles for deterministic output
sorted_files=$(printf '%s\n' "${!file_device_keys[@]}" | sort)

while read -r sops_file; do
  [[ -n "$sops_file" ]] || continue

  # Escape dots for regex (slashes are not special in regex)
  path_regex=$(echo "$sops_file" | sed 's/\./\\./g')

  cat >> "$sops_yaml" <<EOF
  - path_regex: ${path_regex}\$
    key_groups:
      - age:
          # Principals (secrets role)
EOF

  # Add principal keys (sorted by name)
  for name in $(printf '%s\n' "${!principal_age_keys[@]}" | sort); do
    echo "          - ${principal_age_keys[$name]} # ${name}" >> "$sops_yaml"
  done

  echo "          # Device keys (consuming hosts)" >> "$sops_yaml"

  # Add device keys (sorted by host name, deduplicated)
  device_entries="${file_device_keys[$sops_file]}"
  echo "$device_entries" | tr ' ' '\n' | sort -t= -k1 | while IFS='=' read -r hname dkey; do
    [[ -n "$hname" ]] || continue
    echo "          - ${dkey} # ${hname}" >> "$sops_yaml"
  done

done <<< "$sorted_files"

# --- Compare and apply ---
if diff -q "$sops_yaml" ".sops.yaml" >/dev/null 2>&1; then
  echo "[rekey] .sops.yaml is up to date, no changes needed"
  exit 0
fi

echo "[rekey] .sops.yaml has changed:"
diff --color=auto ".sops.yaml" "$sops_yaml" || true

cp "$sops_yaml" ".sops.yaml"
echo "[rekey] Updated .sops.yaml"

# --- Rekey files whose recipients changed ---
echo "[rekey] Running sops updatekeys on all managed files..."

while read -r sops_file; do
  [[ -n "$sops_file" ]] || continue
  if [[ -f "$sops_file" ]]; then
    echo "[rekey] Updating keys: $sops_file"
    sops updatekeys -y "$sops_file"
  else
    echo "[rekey] WARNING: $sops_file not found, skipping updatekeys" >&2
  fi
done <<< "$sorted_files"

echo "[rekey] Done"
